/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#e6e2dd",
        "on-secondary-fixed-variant": "#3c4c25",
        "on-primary-fixed-variant": "#812914",
        "surface-variant": "#e6e2dd",
        "tertiary-fixed": "#ffdea6",
        "on-secondary-fixed": "#121f01",
        "secondary-fixed": "#d6eab5",
        "primary": "#a03f28",
        "error": "#ba1a1a",
        "surface-container-low": "#f7f3ee",
        "tertiary": "#7b5800",
        "outline": "#8a726c",
        "secondary": "#53643a",
        "on-tertiary-fixed": "#271900",
        "secondary-fixed-dim": "#bacd9b",
        "primary-fixed-dim": "#ffb4a3",
        "primary-fixed": "#ffdad2",
        "on-surface-variant": "#56423d",
        "background": "#fdf9f4",
        "on-error-container": "#93000a",
        "outline-variant": "#ddc0ba",
        "on-error": "#ffffff",
        "tertiary-container": "#9a6f07",
        "on-secondary-container": "#596a40",
        "on-secondary": "#ffffff",
        "secondary-container": "#d6eab5",
        "inverse-surface": "#31302d",
        "on-tertiary-container": "#ffffff",
        "on-background": "#1c1c19",
        "on-primary-container": "#120100",
        "tertiary-fixed-dim": "#f3be58",
        "surface-container": "#f1ede8",
        "surface-bright": "#fdf9f4",
        "on-tertiary-fixed-variant": "#5e4200",
        "surface-tint": "#a03f29",
        "surface": "#fdf9f4",
        "surface-container-high": "#ebe8e3",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#3d0700",
        "primary-container": "#c0573e",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#f4f0eb",
        "inverse-primary": "#ffb4a3",
        "on-surface": "#1c1c19",
        "surface-dim": "#ddd9d5"
      },
      fontFamily: {
        "headline": ["Cormorant Garamond", "serif"],
        "body": ["Jost", "sans-serif"],
        "label": ["Jost", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem", 
        "lg": "0.25rem", 
        "xl": "0.5rem", 
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
